import type { LevelDef } from './engine';

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: 'İlk Kıvılcım',
    moves: 30,
    kinds: 4,
    baseScore: 800,
    objectives: [{ type: 'clearAny', target: 15, label: 'Taş Patlat' }],
  },
  {
    id: 2,
    name: 'Sayılı Hamle',
    moves: 20,
    kinds: 4,
    baseScore: 1500,
    objectives: [{ type: 'score', target: 1500, label: 'Skor' }],
  },
  {
    id: 3,
    name: 'Amber Avı',
    moves: 18,
    kinds: 4,
    baseScore: 1200,
    objectives: [{ type: 'collect', kind: 'amber', target: 20 }],
  },
  {
    id: 4,
    name: 'Çizgi Ustası',
    moves: 20,
    kinds: 4,
    baseScore: 1400,
    objectives: [{ type: 'special', specials: ['lineH', 'lineV'], target: 2, label: 'Çizgi Patlatıcı' }],
  },
  {
    id: 5,
    name: 'Kristal Bahçesi',
    moves: 18,
    kinds: 4,
    baseScore: 1500,
    objectives: [{ type: 'collect', kind: 'crystal', target: 25 }],
  },
  {
    id: 6,
    name: 'Ruhun Doğuşu',
    moves: 22,
    kinds: 4,
    baseScore: 1600,
    objectives: [{ type: 'special', specials: ['soul'], target: 1, label: 'Ruh Kristali' }],
  },
  {
    id: 7,
    name: 'Gümbür Gümbür',
    moves: 22,
    kinds: 4,
    baseScore: 1700,
    objectives: [{ type: 'special', specials: ['bomb'], target: 2, label: 'Mağara Bombası' }],
  },
  {
    id: 8,
    name: 'Beşinci Taş',
    moves: 20,
    kinds: 5,
    baseScore: 2500,
    objectives: [{ type: 'score', target: 2500, label: 'Skor' }],
  },
  {
    id: 9,
    name: 'Çifte Hasat',
    moves: 20,
    kinds: 5,
    baseScore: 2200,
    objectives: [
      { type: 'collect', kind: 'moss', target: 30 },
      { type: 'collect', kind: 'lava', target: 30 },
    ],
  },
  {
    id: 10,
    name: 'Mini Zirve',
    moves: 22,
    kinds: 5,
    baseScore: 2400,
    objectives: [
      { type: 'collect', kind: 'amber', target: 30 },
      { type: 'score', target: 2000, label: 'Skor' },
    ],
  },
];
